language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION="~2.3||~3.0"

matrix:
  include:
    - php: 5.3.3
      env: SYMFONY_VERSION=2.3.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.6.*
    - php: 5.5
      env: SYMFONY_VERSION=2.7.* SYMFONY_DEPRECATIONS_HELPER=weak

before_install:
  - composer self-update || true
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
  - COMPOSER_ROOT_VERSION=dev-master composer update $COMPOSER_FLAGS --prefer-source --no-interaction
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
