language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_PHPUNIT_VERSION=6.5
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"

      # Test the latest stable release
    - php: 7.1
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
    - php: 7.3

    # Test LTS versions. This makes sure we do not use Symfony packages with version greater
    # than 3 or 4 respectively. Read more at https://github.com/symfony/lts
    - php: 7.2
      env: DEPENDENCIES="symfony/lts:^3"
    - php: 7.2
      env: DEPENDENCIES="symfony/lts:^4@dev"

      # Latest commit to master
    - php: 7.2
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - composer self-update || true
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - cat composer.json
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable; fi
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install
  - ./.travis/phpcr_odm_doctrine_dbal.sh

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
